# .github/workflows/deploy-all.yml
name: Deploy Full Stack

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: aws-cloud
        type: choice
        options:
          - aws-cloud

jobs:

  backend:
    uses: ./.github/workflows/deploy-service.yml
    with:
      environment: ${{ github.event.inputs.environment }}

  ui:
    needs: backend
    uses: ./.github/workflows/deploy-ui.yml
    with:
      environment: ${{ github.event.inputs.environment }}