name: Flyway Apply
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - stage
          - prod
  push:
    branches: [ "main" ]

jobs:
  build-and-migrate:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Flyway Migrations
        run: |
          ./gradlew flywayMigrate \
          -Dflyway.url=${{ secrets.DB_URL }} \
          -Dflyway.user=${{ secrets.DB_USER }} \
          -Dflyway.password=${{ secrets.DB_PASSWORD }}